model_name: "gpt-3.5-turbo"
input_file: "tests/test.pdf"
output_file_format: "markdown"
source_language: "English"
target_language: "Chinese"
api_key: "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"